image: go1.2
script:
  - mkdir -p $GOPATH/src/gopkg.in/Clever
  - ln -s `pwd` $GOPATH/src/gopkg.in/Clever/optimus.v3
  - make test
notify:
  email:
    recipients:
      - drone@clever.com
  hipchat:
    room: Clever-Dev-CI
    token: {{hipchatToken}}
    on_started: true
    on_success: true
    on_failure: true
